Venv setup
inference-labs-inc/omron-subnet pull request #6
Opened 2024-04-23 14:37 UTC by alex-drocks

use a virtual env for python dependencies

2024-05-03 16:11 UTC, IvanAnishchuk requested changes
Doesn't work in all environments, please double-check.

2024-05-03 16:11 UTC, IvanAnishchuk commented on setup.sh
> +
This probably should be happening before we install btcli... Otherwise running it on vanilla ubuntu instance causes this:

```
btcli not found. Installing btcli...
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

(bare `pip install stuff` is not supposed to work there outside of a VE, which is probably a good idea)

I guess moving pip install bittensor lower than this snippet would be an ok fix.

2024-05-03 16:11 UTC, IvanAnishchuk commented on setup.sh
> +
And venv module is not installed by default on server instances at least. python3-venv should probably be added to the command installing pip above.

2024-05-03 17:11 UTC, alex-drocks commented on setup.sh
> +
Yes you are right, I did not make this PR for every env. I am hoping people with other contexts can test in their env

2024-05-05 09:47 UTC, IvanAnishchuk commented on setup.sh
> +
Well, installing system deps universally is almost impossible. But things starting with venv creation are easy enough to standardize.

Installing global and user packages with pip was always frowned upon though, especially in install scripts meant for non-interactive execution. Let me just show what I mean, I guess...

2024-05-05 16:13 UTC, IvanAnishchuk commented on setup.sh
> +
Can't push here, take a look at alex-drocks/sn2-omron#1

2024-05-20 14:18 UTC, alex-drocks commented on setup.sh
> +
Turns out you were right.

I pushed the fixed code which is basically what you proposed. Thank you @IvanAnishchuk

2024-05-30 06:06 UTC, HudsonGraeme commented
Many thanks for the contribution @alex-drocks! This feature is included in release `0.1.6` and staged to testnet at d568255b72bf6d8fae793f910dd05f61550176d7!

2024-05-30 06:06 UTC, closed without merging